(deftheme shadow "A port of the Neovim shadow theme to Emacs.")

(let ((class '((class color) (min-colors 89)))
      (fg "#E6E7E6")
      (bg "#1D2326")
      (black "#242B2D")
      (black-bright "#485457")
      (red "#BC8F7D")
      (red-bright "#D4A394")
      (green "#96B088")
      (green-bright "#ABC49E")
      (yellow "#CCAC7D")
      (yellow-bright "#E2BF8F")
      (blue "#7E9AAB")
      (blue-bright "#94B1C4")
      (magenta "#A68CAA")
      (magenta-bright "#BC9EC0")
      (cyan "#839C98")
      (cyan-bright "#97B3AF")
      (white "#CED3DC")
      (white-bright "#E8EBF0"))
  (custom-theme-set-faces
   'shadow
   `(default ((,class (:foreground ,fg :background ,bg))))
   `(cursor ((,class (:background ,fg))))
   `(fringe ((,class (:background ,bg))))
   `(mode-line ((,class (:foreground ,fg :background ,black))))
   `(mode-line-inactive ((,class (:foreground ,black-bright :background ,bg))))
   `(line-number ((,class (:foreground ,black-bright :background ,bg))))
   `(line-number-current-line ((,class (:foreground ,green :background ,bg))))
   `(font-lock-builtin-face ((,class (:foreground ,blue-bright))))
   `(font-lock-comment-face ((,class (:foreground ,black-bright))))
   `(font-lock-constant-face ((,class (:foreground ,cyan))))
   `(font-lock-function-name-face ((,class (:foreground ,blue))))
   `(font-lock-keyword-face ((,class (:foreground ,magenta))))
   `(font-lock-string-face ((,class (:foreground ,green))))
   `(font-lock-type-face ((,class (:foreground ,cyan-bright))))
   `(font-lock-variable-name-face ((,class (:foreground ,magenta-bright))))
   `(minibuffer-prompt ((,class (:foreground ,yellow))))
   `(error ((,class (:foreground ,red))))
   `(warning ((,class (:foreground ,yellow))))
   `(success ((,class (:foreground ,green))))))

(provide-theme 'shadow)
