;;; elfeed.el --- Configurazione package `elfeed'

;;; Commentary:
;; package usato per la consultazione di feed RSS.  Per una navigazione web
;; migliore, senza social media.

;; TODO: cancel all the link
;; link utili elfeed
;; https://cundy.me/post/elfeed/
;; https://nullprogram.com/blog/2015/12/03/
;; https://nullprogram.com/blog/2013/11/26/
;; https://www.maketecheasier.com/use-emacs-for-rss-with-elfeed/

;; cool stuff
;; https://lainzine.org/about
;; https://neocities.org/browse
;; https://districts.neocities.org/
;; https://goblin-heart.net/sadgrl/reading/
;; https://crushcapitalism.neocities.org/theory/combat-liberalism
;; https://gifypet.neocities.orq2g/
;; https://melonking.net/
;; https://distantskies.neocities.org/
;; https://youtu.be/zswyWBtF-7Y
;; https://100r.co/site/uxn.html
;; https://wiki.xxiivv.com/site/home.html

;;; Code:

(require 'seq)

(use-package elfeed
  :ensure t
  :config
  ;; The RSS links saved in `elfeed-feeds' are the ones in the file
  ;; `~/.rssfeed'.  If any link in the file is commented out with `#', it is
  ;; automatically ignored.  This configuration supports `autotags', which can
  ;; be retrieved directly from the `~/.rssfeed' file
  (setq elfeed-feeds
        (let ((rss-filepath "~/.rssfeed"))
          (when (file-exists-p rss-filepath)
            (with-temp-buffer
              (insert-file-contents rss-filepath)
              ;; read each line from file
              (let ((links-from-file (split-string (buffer-string) "\n" t))
                    (accepted-links nil))
                (mapc (lambda (line)
                        ;; ignore commented lines
                        (when (not (string-match-p "^[[:space:]]*#[[:space:]]+[a-zA-Z[:punct:]]+" line))
                          (add-to-list 'accepted-links
                                       ;; format line from text to string in (link &rest autotags)
                                       (let ((formatted-list (string-split line "[[:space:]|]+")))
                                         (cons (car formatted-list) ;; link
                                               (setcdr formatted-list
                                                       ;; extract each tag as a symbol, removing the useless tag '##
                                                       ;; generated by empty string
                                                       (remq '##
                                                             ;; remove the comments on the same line that start with #
                                                             (seq-take-while (lambda (tag) (not (eq tag '\#)))
                                                                             (mapcar (lambda (tag) (intern (string-trim tag)))
                                                                                     (cdr formatted-list))))))))))
                      links-from-file)
                accepted-links)))))
  ;; (setq elfeed-feeds
  ;;       (let ((rss-filepath "~/.rssfeed"))
  ;;         (when (file-exists-p rss-filepath)
  ;;           (with-temp-buffer
  ;;             (insert-file-contents rss-filepath)
  ;;             ;; read each line from file
  ;;             (let ((links-from-file (split-string (buffer-string) "\n" t))
  ;;                   (accepted-links nil))
  ;;               (mapc (lambda (line)
  ;;                       ;; ignore commented lines
  ;;                       (when (null (string-match-p "^[[:space:]]*#[[:space:]]+[a-zA-Z[:punct:]]+" line))
  ;;                         (add-to-list 'accepted-links
  ;;                                      ;; format line from text to string in (link &rest autotags)
  ;;                                      (let ((formatted-list (string-split line "[[:space:]|]+")))
  ;;                                        (cons (car formatted-list)
  ;;                                              (setcdr formatted-list
  ;;                                                      ;; extract each tag as a symbol, removing the useless tag '##
  ;;                                                      ;; generated by empty string
  ;;                                                      (remq '## (mapcar (lambda (tag) (intern (string-trim tag)))
  ;;                                                                        (cdr formatted-list)))))))))
  ;;                     links-from-file)
  ;;               accepted-links)))))
  )
;;; elfeed.el ends here.
