#+TITLE: Dotfiles
#+AUTHOR: 3le4ms1

Configuration files for things, across different systems.

* Deploy
  To install the configuration just run the installation script in the
  terminal. On =Windows= it must be runned as administrator.

  The deploy scripts must be executed in a directory directly under the user
  home, even if executed as root. For example:
  #+begin_src bash
    ~/.config/install.sh
  #+end_src

** Linux
   #+begin_src bash
     $ ./install.sh
   #+end_src

** Windows
   The =sudo= script can be installed via the [[https://www.scoop.sh][scoop]] package manager.
   In alternative the script can be just runned in ad elevated shell.

   #+begin_src powershell
     PS> sudo install.ps1
     PS(root)> install.ps1
   #+end_src

* Program specific things
** Emacs
   When starting =emacs= for the first time on a clean platform, there are some
   operations to be executed:
   - running =emacs= as a daemon to create the =server= file in the
     =~/.emacs.d/server= directory, by running the command:
     #+begin_src bash
       $ emacs --daemon
     #+end_src
   - install all of the packages that are missing, using emacs function =M-x
     package-install-selected-packages RET=. It is useful to run the command
     multiple times, in case of errors regard too many files opened or something
     else.
