(cd (getenv "HOME"))
(setq default-directory (getenv "HOME"))
(setq command-line-default-directory (getenv "HOME"))
(load-theme 'leuven-dark)
(display-line-numbers-mode)
(global-set-key (kbd "C-\\") #'comment-line)
(global-set-key (kbd "C-ù") #'comment-line)
(set-face-attribute 'default 'nil :height 150)
(menu-bar-mode -1)
(tab-bar-mode -1)
(tool-bar-mode -1)
(setq ring-bell-function 'ignore)
